
package lm.solution.web.config.jaxwsclient;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SquareRootServerImplService", targetNamespace = "http://ri.jaxws.service.solution.lm/", wsdlLocation = "http://localhost:8083/ri/SquareRootServer?wsdl")
public class SquareRootServerImplService
    extends Service
{

    private final static URL SQUAREROOTSERVERIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SQUAREROOTSERVERIMPLSERVICE_EXCEPTION;
    private final static QName SQUAREROOTSERVERIMPLSERVICE_QNAME = new QName("http://ri.jaxws.service.solution.lm/", "SquareRootServerImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8083/ri/SquareRootServer?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SQUAREROOTSERVERIMPLSERVICE_WSDL_LOCATION = url;
        SQUAREROOTSERVERIMPLSERVICE_EXCEPTION = e;
    }

    public SquareRootServerImplService() {
        super(__getWsdlLocation(), SQUAREROOTSERVERIMPLSERVICE_QNAME);
    }

    public SquareRootServerImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SQUAREROOTSERVERIMPLSERVICE_QNAME, features);
    }

    public SquareRootServerImplService(URL wsdlLocation) {
        super(wsdlLocation, SQUAREROOTSERVERIMPLSERVICE_QNAME);
    }

    public SquareRootServerImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SQUAREROOTSERVERIMPLSERVICE_QNAME, features);
    }

    public SquareRootServerImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SquareRootServerImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SquareRootServer
     */
    @WebEndpoint(name = "SquareRootServerImplPort")
    public SquareRootServer getSquareRootServerImplPort() {
        return super.getPort(new QName("http://ri.jaxws.service.solution.lm/", "SquareRootServerImplPort"), SquareRootServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SquareRootServer
     */
    @WebEndpoint(name = "SquareRootServerImplPort")
    public SquareRootServer getSquareRootServerImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ri.jaxws.service.solution.lm/", "SquareRootServerImplPort"), SquareRootServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SQUAREROOTSERVERIMPLSERVICE_EXCEPTION!= null) {
            throw SQUAREROOTSERVERIMPLSERVICE_EXCEPTION;
        }
        return SQUAREROOTSERVERIMPLSERVICE_WSDL_LOCATION;
    }

}
